// apollonian.js — the Apollonian gasket: recursive circle packing, drawn
// entirely on the GPU by a fragment shader (a single fullscreen quad).
//
// APPROACH: (A) shader fractal via repeated CIRCLE INVERSIONS.
//
// THE MATH —
//   • Apollonian gasket: start with three mutually tangent circles; in every
//     curvilinear-triangle gap a new tangent circle is inscribed, and you
//     recurse forever. The radius of each new circle follows the DESCARTES
//     CIRCLE THEOREM: with curvature k = 1/r,
//         k4 = k1 + k2 + k3 ± 2·sqrt(k1·k2 + k2·k3 + k3·k1).
//     (We cite it as the generative rule; the renderer below realises the same
//     infinitely-nested set by a conformal-tiling method instead of enumerating
//     circles, which is what gives the "infinite detail" look.)
//   • INVERSION RENDER: the gasket is invariant under the group generated by
//     inversion in its three mutual-tangent circles. So we fold the plane: at
//     each step reflect z across a unit cell (mod), then if z lies inside the
//     generating circle of radius r about a point c, invert it,
//         z -> c + (z - c) * r^2 / dot(z-c, z-c),
//     tracking the accumulated scale so the running min-distance is a proper
//     conformal distance estimate. Accumulating min(|z| near the tangency
//     loci) draws the gasket's nested rings with true infinite nesting.
//     This is the well-known "apollonian"/"kleinian" folding shader family
//     (cf. Inigo Quilez "Apollonian", Syntopia/Knighty fold-and-invert lore).
//   • The slow zoom + drift makes it filmable; colour ramps by curvature
//     depth (cyan -> magenta -> amber) on near-black — no purple-dominant cast.
//
// Routed through the PS1 pipeline ({srgb:false}; the shader gamma-corrects its
// own output) so the uv resolution uniform must equal the low-res RT (syncRes).

import * as THREE from "three";
import { makeRenderer, onResize, loop, fpsMeter, liftVeil, bindRange, reducedMotion, setVariantCycler } from "./common.js";
import { makePS1Pipeline } from "./ps1.js";

const canvas = document.getElementById("scene");
const renderer = makeRenderer(canvas);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.3)); // inversion fractal is heavy — cap harder

const scene = new THREE.Scene();
const camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1); // unused transform; quad is in clip space

const uniforms = {
  uResolution: { value: new THREE.Vector2(innerWidth, innerHeight) },
  uTime: { value: 0 },
  uDepth: { value: 14 },        // inversion iterations ≈ recursion depth
  uZoom: { value: 1.0 },        // view zoom (animated dive)
  uPan: { value: new THREE.Vector2(0.0, 0.0) },
  uK: { value: 1.42 },          // seed curvature / cell radius — the "seed circle" knob
  uScheme: { value: 0 },        // colour scheme index
};

const vert = /* glsl */ `
  void main() { gl_Position = vec4(position.xy, 0.0, 1.0); }
`;

const frag = /* glsl */ `
  precision highp float;

  uniform vec2  uResolution;
  uniform float uTime;
  uniform int   uDepth;
  uniform float uZoom;
  uniform vec2  uPan;
  uniform float uK;
  uniform int   uScheme;

  const int MAX_DEPTH = 28;

  // three colour ramps over near-black; cyan -> magenta -> amber families
  // (scheme 0 vivid, 1 cool, 2 warm) — none purple-dominant.
  vec3 ramp(float t, int s) {
    t = clamp(t, 0.0, 1.0);
    vec3 a, b, c, d, e;
    if (s == 1) {            // cool: teal -> cyan -> ice -> white
      a = vec3(0.02, 0.10, 0.14); b = vec3(0.04, 0.52, 0.62);
      c = vec3(0.16, 0.85, 0.96); d = vec3(0.55, 0.95, 1.00);
      e = vec3(0.92, 1.00, 1.00);
    } else if (s == 2) {     // warm: ember -> amber -> gold -> cream
      a = vec3(0.10, 0.03, 0.02); b = vec3(0.62, 0.16, 0.06);
      c = vec3(1.00, 0.50, 0.12); d = vec3(1.00, 0.80, 0.30);
      e = vec3(1.00, 0.96, 0.84);
    } else {                 // vivid: cyan -> magenta -> amber -> white
      a = vec3(0.02, 0.10, 0.16); b = vec3(0.16, 0.82, 0.96);
      c = vec3(1.00, 0.20, 0.62); d = vec3(1.00, 0.66, 0.22);
      e = vec3(1.00, 0.95, 0.85);
    }
    t *= 4.0;
    if (t < 1.0) return mix(a, b, t);
    if (t < 2.0) return mix(b, c, t - 1.0);
    if (t < 3.0) return mix(c, d, t - 2.0);
    return mix(d, e, t - 3.0);
  }

  // Apollonian gasket distance estimate via fold + circle inversion.
  // Returns the conformal distance to the gasket curves in .x and a
  // depth/curvature trap in .y (how many inversions actually fired).
  vec2 apollonian(vec2 z) {
    float scale = 1.0;          // accumulated derivative (for the DE)
    float trap = 0.0;           // orbit trap on running radius (curvature feel)
    float kk = uK;              // cell radius / seed curvature knob
    float depthFired = 0.0;
    for (int i = 0; i < MAX_DEPTH; i++) {
      if (i >= uDepth) break;
      // fold the plane into a unit cell centred on the origin
      z = mod(z + 1.0, 2.0) - 1.0;
      float d2 = dot(z, z);
      float k = kk / max(d2, 1e-6);  // inversion: z -> z * (r^2 / |z|^2)
      // only invert when inside the generating circle (keeps the gasket gaps)
      if (d2 < kk) {
        z *= k;
        scale *= k;
        depthFired += 1.0;
      }
      trap = min(trap == 0.0 ? 1e9 : trap, abs(length(z) - 0.5));
    }
    // distance to the nested circle loci, conformally corrected
    float de = (abs(length(z) - 1.0)) / abs(scale);
    return vec2(de, depthFired / float(max(uDepth, 1)));
  }

  void main() {
    // normalised screen coords; zoom + pan into the gasket
    vec2 uv = (gl_FragCoord.xy * 2.0 - uResolution) / uResolution.y;
    vec2 p = uv / max(uZoom, 1e-4) + uPan;

    vec2 res = apollonian(p);
    float de = res.x;
    float trapDepth = res.y;

    // pixel footprint for crisp-but-aa lines as we zoom
    float px = 1.6 / (uResolution.y * max(uZoom, 1e-4));
    // draw the gasket curves: bright where de is small (on a circle)
    float line = 1.0 - smoothstep(0.0, px * 3.0, de);
    // soft glow halo around the curves to keep deep nesting readable
    float glow = exp(-de * 90.0) * 0.6 + exp(-de * 18.0) * 0.25;

    // colour by inversion depth (≈ curvature): deeper => further along ramp
    float tcol = clamp(trapDepth * 0.85 + de * 8.0, 0.0, 1.0);
    vec3 base = ramp(tcol, uScheme);

    // near-black background with a faint cool wash so it never reads as purple
    vec3 bg = mix(vec3(0.006, 0.010, 0.016), vec3(0.012, 0.028, 0.040),
                  smoothstep(-1.0, 1.0, uv.y));

    vec3 col = bg;
    col += base * glow;                 // the nested haze
    col += base * line * 1.35;          // the crisp circle strokes
    col += vec3(0.10, 0.40, 0.55) * glow * 0.4; // cyan ambient lift

    // gentle vignette + tonemap
    float vig = 1.0 - 0.26 * dot(uv * 0.5, uv * 0.5);
    col *= vig;
    col = col / (col + vec3(1.0));      // Reinhard
    col = pow(col, vec3(0.4545));       // gamma (PS1 pass uses srgb:false)

    gl_FragColor = vec4(col, 1.0);
  }
`;

const material = new THREE.ShaderMaterial({ uniforms, vertexShader: vert, fragmentShader: frag });
scene.add(new THREE.Mesh(new THREE.PlaneGeometry(2, 2), material));

// PS1 pass: render the gasket into a 1/4-res target → nearest upscale + 4×4
// Bayer dither = chunky PS1 circles. srgb:false because this shader already
// gamma-corrects its own output; the uv resolution uniform must track the RT.
const ps1 = makePS1Pipeline(renderer, scene, camera, { scale: 4, levels: 32, srgb: false });
const syncRes = () => uniforms.uResolution.value.set(ps1.renderTarget.width, ps1.renderTarget.height);
syncRes();

// ---------- view: zoom + drift (the "camera" is just uZoom/uPan) ----------
const HOME_ZOOM = 1.0, HOME_PAN = new THREE.Vector2(0.0, 0.0);
let zoom = HOME_ZOOM, targetZoom = HOME_ZOOM;
const pan = HOME_PAN.clone();
const targetPan = HOME_PAN.clone();
let dragging = false, lastX = 0, lastY = 0;

function updateView() {
  zoom += (targetZoom - zoom) * 0.12;
  pan.x += (targetPan.x - pan.x) * 0.12;
  pan.y += (targetPan.y - pan.y) * 0.12;
  uniforms.uZoom.value = zoom;
  uniforms.uPan.value.copy(pan);
  if (zmEl) zmEl.textContent = zoom.toFixed(2);
}

canvas.addEventListener("pointerdown", (e) => {
  dragging = true; lastX = e.clientX; lastY = e.clientY;
  canvas.setPointerCapture(e.pointerId);
  diving = false; diveBtn.classList.remove("active");
});
canvas.addEventListener("pointermove", (e) => {
  if (!dragging) return;
  // pan in math-space, scaled by zoom so it feels 1:1 on screen
  targetPan.x -= (e.clientX - lastX) * 0.0022 / zoom;
  targetPan.y += (e.clientY - lastY) * 0.0022 / zoom;
  lastX = e.clientX; lastY = e.clientY;
});
canvas.addEventListener("pointerup", () => (dragging = false));
canvas.addEventListener("wheel", (e) => {
  e.preventDefault();
  targetZoom = Math.max(0.4, Math.min(40.0, targetZoom * (1.0 - e.deltaY * 0.0012)));
}, { passive: false });

// ---------- panel ----------
const zmEl = document.getElementById("zm");
const dpEl = document.getElementById("dp");

let curDepth = 14;
bindRange("depth", (v) => { curDepth = Math.round(v); uniforms.uDepth.value = curDepth; if (dpEl) dpEl.textContent = curDepth; }, (v) => Math.round(v));

let diving = !reducedMotion;
const diveBtn = document.getElementById("dive");
diveBtn.classList.toggle("active", diving);
diveBtn.addEventListener("click", () => {
  diving = !diving;
  diveBtn.classList.toggle("active", diving);
});

let drifting = false;
const driftBtn = document.getElementById("drift");
driftBtn.addEventListener("click", () => {
  drifting = !drifting;
  driftBtn.classList.toggle("active", drifting);
});

document.getElementById("reset").addEventListener("click", () => {
  targetZoom = HOME_ZOOM;
  targetPan.set(HOME_PAN.x, HOME_PAN.y);
});

// ↑/↓ cycle hand-picked seed curvatures + colour schemes (variation in-place)
const PRESETS = [
  { k: 1.42, scheme: 0, name: "vivid · k 1.42" },
  { k: 1.20, scheme: 1, name: "cool · k 1.20" },
  { k: 1.62, scheme: 2, name: "warm · k 1.62" },
  { k: 1.00, scheme: 0, name: "dense · k 1.00" },
  { k: 1.85, scheme: 1, name: "open · k 1.85" },
];
let presetIdx = 0;
setVariantCycler((dir) => {
  presetIdx = (presetIdx + dir + PRESETS.length) % PRESETS.length;
  const pre = PRESETS[presetIdx];
  uniforms.uK.value = pre.k;
  uniforms.uScheme.value = pre.scheme;
  return pre.name;
});

// expose diagnostics for the harness
window.__diag = () => JSON.stringify({ mode: "shader", depth: curDepth });

// ---------- resize / loop ----------
onResize(renderer, camera, () => { ps1.setSize(); syncRes(); });

const meter = fpsMeter(document.getElementById("fps"));
let booted = false;

loop((dt, elapsed) => {
  meter(dt);
  uniforms.uTime.value = elapsed;
  if (diving && !reducedMotion) {
    // slow oscillating dive into the packing, then back out (filmable)
    targetZoom = 1.0 + 7.0 * (0.5 - 0.5 * Math.cos(elapsed * 0.10));
  }
  if (drifting && !reducedMotion) {
    targetPan.x = 0.18 * Math.sin(elapsed * 0.07);
    targetPan.y = 0.18 * Math.cos(elapsed * 0.05);
  }
  updateView();
  ps1.render();
  if (!booted) { booted = true; liftVeil(); }
});
